### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [Michael-Bezzina/Bezzina_CSCI2270_FinalProject#1]
Need documentation and description of what functions do. Also none of the info required by the final project writeup is in the readme file

**Comment by Michael-Bezzina** [comment]
Hey, so I updated the readme file, sorry about that. As for the
descriptions, would you like me to put comments in the code itself or send
you info over email?

**Comment by ghost** [comment]
It's fine, it wasn't a big deal! And you should put them in the code, that
was one of the things that it said to look for in the evaluations. I'm just
trying to help you and show you what you did wrong so that when the TA
grades it at the very end everything is correct.

Adam

**Comment by Michael-Bezzina** [comment]
Thank you for giving me the heads up! I've updated the code, but am
completely new at uploading files to gitHub so I'll either bug a friend or
TA about it tomorrow, which will hopefully still give you enough time to
look it over.

**Comment by Michael-Bezzina** [comment]
I think I managed to figure it out. Hopefully it's a bit more clear.
